version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8808:80"
    command: bash -c "composer install && apache2-foreground"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_db
      MYSQL_USER: mvc_user
      MYSQL_PASSWORD: mvc_password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3303:3306"
    restart: unless-stopped